### ISSUE TITLE
winget support 

### ISSUE THREAD

**Issue by binyaminyblatt** [vladimir-kotikov/clink-completions#131]
i dont know lua but i wrote this
https://gist.github.com/binyaminyblatt/9df5a0adcbb31307c9d735ae462b694c
i dont know why its isnt working

**Comment by binyaminyblatt** [comment]
i just updated my script it works now

**Comment by rashil2000** [comment]
Can you make a pull request with your script so that it gets merged?

**Comment by binyaminyblatt** [comment]
I messed up my clone of the repo but I don't want to delete it and re-clone it because I have some stuff in there can you do it￼￼

**Comment by rashil2000** [comment]
You can create a new separate branch, rebase it with upstream master, and send your PR from there. Your own changes will not get affected, they'll stay.

**Comment by chrisant996** [comment]
Thanks for sharing this.  I'll see about adding to the repo.

**Comment by chrisant996** [comment]
It was a good start at an argmatcher for winget, thank you for sharing it!  It was missing a lot of things, so I decided to write a new one that covers everything that's documented in the online help for winget.

Closing because it is added in the dev branch, and closing it helps me keep track of the remaining work for the next release (which will include the dev changes).

P.S.  There is a `winget complete` command that's supposed to be able to generate completions.  But it generates an empty list of matches for many different things, so it ended up not being useful.
