### ISSUE TITLE
"match generator failed" when putting space

### ISSUE THREAD

**Issue by Qrzysio** [vladimir-kotikov/clink-completions#138]
I have upgraded Cmder to the latest version recently. I get an error when putting space after `git` command. 

```
λ git
match generator failed:
c:\Program Files\cmder/vendor/clink-completions/git.lua:81: attempt to perform arithmetic on local 's' (a nil value)
stack traceback:
        c:\Program Files\cmder/vendor/clink-completions/git.lua:81: in function <c:\Program Files\cmder/vendor/clink-completions/git.lua:68>
        ?: in function <?:397>
        ?: in function <?:380>
        (...tail calls...)
        ?: in function <?:36>
        [C]: in function 'xpcall'
        ?: in function <?:35>
s
On branch master
nothing to commit, working tree clean
```

Video: https://streamable.com/80g02g

How to fix it?

**Comment by simaek** [comment]
I have encountered the same problem when using `scoop uninstall`.

**Comment by chrisant996** [comment]
From reading the git.lua file, the error is happening because the output from `git config --get-regexp alias` has at least one line that contains no space character.

Can you share the output from `git config --get-regexp alias`?

My PR #149 happens to include a fix for that.  But it is beginning to look like Vladimir has abandoned this repo, as the PR has been waiting for 19 days and the last time Vladimir posted in this repo was in September 2021.

I will have to coordinate with the Cmder team about making my fork into the de facto main fork.

**Comment by chrisant996** [comment]
This should be coming in the next release, probably within the next 2 weeks.

**Comment by chrisant996** [comment]
Closing because #149 has been merged. There is some more work to do before the next release is ready, though.
