### ISSUE TITLE
git.lua:155: attempt to call upvalue 'w' (a nil value)

### ISSUE THREAD

**Issue by sebthom** [vladimir-kotikov/clink-completions#160]
Trying to use clink-completions with clink results in

```
> clink installscripts C:\apps\tools\clink-completions
Script path 'C:\apps\tools\clink-completions' installed.

...clink\clink-completions\git.lua:155: attempt to call upvalue 'w' (a nil value)
```

I tried different clink versions but the error persists.

**Comment by sebthom** [comment]
This happens because another clink completion packages was installed which also defined a `tables.lua` module in the global namespace. So maybe it might be a good idea to register the files under `modules` via a dedicated namespace.

**Comment by chrisant996** [comment]
> This happens because another clink completion packages was installed which also defined a `tables.lua` module in the global namespace. So maybe it might be a good idea to register the files under `modules` via a dedicated namespace.

It looks like there are two copies of clink-completions installed.

One in "...clink\clink-completions\".
And one in "C:\apps\tools\clink-completions".

Can you clarify how you would register files under dedicated namespaces in Lua?  I don't understand how one would do that in Lua.

**Comment by sebthom** [comment]
> It looks like there are two copies of clink-completions installed.

No, I shortened the path when creating the issue. There is only one installation.

> Can you clarify how you would register files under dedicated namespaces in Lua? I don't understand how one would do that in Lua.

I fixed it like this on the other end: https://github.com/sebthom/more-clink-completions/commit/d8d9ce557458b66d98a8e10d9b4ee3fc48a2084b

So you basically create a subfolder in `modules`, e.g. `clink_completions` or something else and then reference the modules like `require("clink_completions.tables")` instead of `require("tables")`

**Comment by chrisant996** [comment]
Oh, I see.  That's no different than simply renaming `modules` to `clink_completions_modules`.  It isn't a "namespace" per se, it just uses a more unique directory name than "modules".  I'm cautious about making that change in `clink-completions` itself, since it is a breaking change that can lead to breaking other scripts and breaking clink-completions itself if someone updates it by unzipping the .zip file.

What is the other clink completions package that has a `modules\tables.lua` script, but is not the `clink-completions` package?

**Comment by sebthom** [comment]
> Oh, I see. That's no different than simply renaming `modules` to `clink_completions_modules`.

This would not solve the problem as the `tables` module will still be registered at top-level. If you however introduce a subdirectory but continue to put the parent dir, i.e. `modules` on the lua path, then you can reference the tables module in a qualified way.

> What is the other clink completions package that has a `modules\tables.lua` script, but is not the `clink-completions` package?

Mine :) https://github.com/sebthom/more-clink-completions/ and I mitigated the issue from my side via https://github.com/sebthom/more-clink-completions/commit/d8d9ce557458b66d98a8e10d9b4ee3fc48a2084b

**Comment by chrisant996** [comment]
@sebthom ahhh ok I see, now, thanks for explaining.

At this point it would be a breaking change, and I'm cautious about making those, since they tend to be disruptive and result in frustration and lost time for people (including myself, to answer questions and troubleshoot, etc).

But I'm still a little confused:

It sounds like your more-clink-completions may be similar to clink-completions.  But it has a `tables.lua` module in a different module directory, and its different module isn't a copy and works differently?  I'd have imagined it would either copy `tables.lua` or use a different module name if it knew the module name conflicted.  Which I suppose is the point -- the conflict wasn't originally noticed.

**Comment by sebthom** [comment]
Well, I don't know but my repo used to work in conjunction with clink-completions with no problems, after installing a new version of clink-completions without having modified my repo I got the error described. Maybe because of this change https://github.com/vladimir-kotikov/clink-completions/commit/2ae10839df52a48da1881c925403035176b80cc2

The tables.lua I created is different, it is not a copy.

**Comment by chrisant996** [comment]
> Well, I don't know but my repo used to work in conjunction with clink-completions with no problems, after installing a new version of clink-completions without having modified my repo I got the error described. Maybe because of this change [2ae1083](https://github.com/vladimir-kotikov/clink-completions/commit/2ae10839df52a48da1881c925403035176b80cc2)
> 
> The tables.lua I created is different, it is not a copy.

How would it be related to that commit?  That commit didn't change anything about the modules path.  It only refactored a line so that it could reuse the parent path, instead of computing the parent path twice.

You mentioned using `clink installscripts` as the way you installed a new version of clink-completions.

That's the cause.  Previously `clink installscripts` must not have been used to install it.  The installscripts locations are loaded after all other scripts have been loaded.  So `git.lua` from an installscripts directory ends up loading the `tables.lua` module from your other scripts.

Which also means that in the past, your scripts must have been accidentally loading the clink-completions copy of `tables.lua` instead of their own copy?
