### ISSUE TITLE
[Feature Request] Add support for `dotnet add [<PROJECT>] [command] [options]`

### ISSUE THREAD

**Issue by DarkRRb** [vladimir-kotikov/clink-completions#192]
like `dotnet add Demo package Microsoft.Extensions.Logging`

Add the `Microsoft.Extensions.Logging` package for the `./Demo/Demo.csproj`

**Comment by chrisant996** [comment]
@DarkRRb I think what you mean is, you want to be able to complete the optional `[<PROJECT>]` argument before the `package` command, and then have the `package` command still be supported after the project name.

In other words,
- `dotnet add package Microsoft.Extensions.Logging` is already supported, and
- `dotnet add PROJECT package Microsoft.Extensions.Logging` is what you want.

**Comment by chrisant996** [comment]
@DarkRRb please update your clink-completions scripts to [v0.6.1](https://github.com/vladimir-kotikov/clink-completions/releases/tag/v0.6.1) and try the new updated `dotnet` completions.  If I'm understanding the request properly, then it should do what you want now.

**Comment by DarkRRb** [comment]
I'm sorry I didn't make my point clear.

I actually meant to type `dotnet add` and then press `Tab`

Show the following tips

1. folder, with *.csporj file inside
2. *.csporj file
3. `package`
4. `reference`

If this is difficult to implement, it is also possible to just display all folders and files and `package` and `reference`

**Comment by chrisant996** [comment]
That's not how the `bash` completions for dotnet work, and it's not how the `dotnet complete` command itself interprets input.

The dotnet program has built-in support for generating completions, and the dotnet program itself does not generate file completions where you've requested.

> Show the following tips

Mixing commands `package` and `reference` with directory names and file names gets messy.  It can become difficult to even see/find the `package` and `reference` commands.  I'll consider turning off automatic sorting, and instead force `package` and `reference` to the beginning of the list (and use a different color when colors are enabled), so that directories and files are listed after the command names.

> *.csporj file

Listing *.csproj files wouldn't be complete; various other file extensions can also be relevant.  At a minimum, *.vbproj and *.fsproj.  But the documentation also mentions solution files, and there are probably other file types that are relevant as well.

> folder, with *.csporj file inside

Listing only folders that contain *.csproj files is problematic because it requires recursively scanning the file system, which can often be slow.  Normally all folders are listed as possible completions.

**Comment by chrisant996** [comment]
I've added what you requested.  I'm not convinced it's a very usable approach, but I've added it.

You'll have to download the dotnet.lua file again.  I'm not going to push a new release just for this tweak.

**Comment by DarkRRb** [comment]
> That's not how the `bash` completions for dotnet work, and it's not how the `dotnet complete` command itself interprets input.
> 
> The dotnet program has built-in support for generating completions, and the dotnet program itself does not generate file completions where you've requested.

But you can use folders or files as valid input here, and of course you can stick with the same completion procedures as bash or dotnet.

> > *.csporj file
> 
> Listing *.csproj files wouldn't be complete; various other file extensions can also be relevant. At a minimum, *.vbproj and *.fsproj. But the documentation also mentions solution files, and there are probably other file types that are relevant as well.
> 
> > folder, with *.csporj file inside
> 
> Listing only folders that contain *.csproj files is problematic because it requires recursively scanning the file system, which can often be slow. Normally all folders are listed as possible completions.

Maybe it would be a good solution to just list all folders and files?

**Comment by DarkRRb** [comment]
> I've added what you requested. I'm not convinced it's a very usable approach, but I've added it.
> 
> You'll have to download the dotnet.lua file again. I'm not going to push a new release just for this tweak.

I did a simple test and found a small problem. When the parameter after `add` is a folder or file, the next parameter does not need to display the folder and file because it can only be used once.

**Comment by DarkRRb** [comment]
Wrong:

![image](https://github.com/user-attachments/assets/f40e821d-38a9-402b-b9ea-53af7343f538)

Correct:

![image](https://github.com/user-attachments/assets/8c865cb8-6de2-40c2-9a3d-7672ff3c3a43)

**Comment by chrisant996** [comment]
> > That's not how the `bash` completions for dotnet work, and it's not how the `dotnet complete` command itself interprets input.
> > 
> > The dotnet program has built-in support for generating completions, and the dotnet program itself does not generate file completions where you've requested.
> 
> But you can use folders or files as valid input here, and of course you can stick with the same completion procedures as bash or dotnet.

Just to be clear: you're asking to **not** use the same completion procedure as bash.

You're asking for it to behave differently in clink-completions than how it behaves in any of the other shells.

E.g. bash simply runs `dotnet complete --position {cursor position} {command line}`, and the `dotnet complete` command chooses to not generate directory or file name completions there.

It's possible to make clink-completions behave differently, but there's probably some intentional reasons why none of the other shells behave that way (and why the `dotnet complete` helper command itself doesn't -- try manually invoking it and see, or try in bash).

I've hooked it up how you requested, but there are definitely some messy quirks as a result.  Normally I intentionally avoid doing it that way, because in other cases it has led to other/opposite complaints.

**Comment by chrisant996** [comment]
> > I've added what you requested. I'm not convinced it's a very usable approach, but I've added it.
> > 
> > You'll have to download the dotnet.lua file again. I'm not going to push a new release just for this tweak.
> 
> I did a simple test and found a small problem. When the parameter after `add` is a folder or file, the next parameter does not need to display the folder and file because it can only be used once.

Yes. I'll adjust that maybe next week.

**Comment by DarkRRb** [comment]
OK, thank you
