### ISSUE TITLE
Improve yarn run completions

### ISSUE THREAD

**Issue by jods4** [vladimir-kotikov/clink-completions#74]
Unlike NPM, `yarn run` can run local modules in addition to `project.json` scripts.

I managed to do that locally with the following simple changes: 
```lua
local bins = matchers.create_files_matcher('node_modules/.bin/*.')
-- ... skip some parser code
"run"..parser({bins, scripts}),
```

And this works, with 2 limitations that I am not sure how to fix:
- I would like to color the scripts to make them more prominent. I tried to `color_text` the results but it didn't work.
- it seems `create_files_matcher` returns `.` and `..`. `create_dirs_matcher` has some code to avoid that, it should probably be added to `create_files_matcher` as well.

**Comment by vladimir-kotikov** [comment]
@jods4, thanks for the suggestion! Could you take a look at the linked PR? I'm not actively using Cmder these days and i'm not a yarn user so I can't verify the changes right now

**Comment by jods4** [comment]
@vladimir-kotikov This is exactly what I have here, works well for me!

Is it possible to colorize the completions? 
If it is I would like to emphasize the scripts results in blue but I wasn't sure how to do it.

**Comment by vladimir-kotikov** [comment]
Nice, thanks for verification!

> Is it possible to colorize the completions?

Unfortunately this is not possible because readline library that prints completions under the hood of clink cuts out all ANSI escape sequences.

To differentiate one options from another you might use `clink.match_display_filter` and add some additional symbols to selected completions (e.g. prepend ones corresponding to executables in `.bin` with `>` or `*`). See https://github.com/vladimir-kotikov/clink-completions/blob/master/git.lua#L158-L165 for example of this approach

**Comment by vladimir-kotikov** [comment]
Closing this for now. Please open a separate PR if you're going to update/improve the visual behavior for completions.
